### ISSUE TITLE
Filtering only by entity logical nam

### ISSUE THREAD

**Issue by ChadAlt** [MscrmTools/MsCrmTools.SecurityRelated#14]
[I think it would be really helpful if we could search by the entity logical name or display name. For example, I must search for incident when I want to find the privileges for the Case entity.]

---
- Deployment: Online
- DB Version: 9.2.21034.182
- Connection Controls Version: 1.2021.2.40
- XrmToolBox Version: 1.2021.4.47
- Tool Version: 1.2020.11.4

**Comment by MscrmTools** [comment]
Can you bore use for which tool you want this improvement?

**Comment by ChadAlt** [comment]
Privileges Discovery is the tool I'm referencing.

- Chad Althaus
