### ISSUE TITLE
Privileges are not displayed correctly and roles are missing in the list

### ISSUE THREAD

**Issue by n0rthface** [MscrmTools/MsCrmTools.SecurityRelated#18]
Using version 1.2022.10.8, I discovered that privileges are not displayed correctly anymore.
When I select to display privileges greater than User level, privileges are displayed on level less than setup in the role. When the privilege is set to be P/C, only BU level is displayed.
Moreover, roles are missing in the list of "Roles that match selection". I am missing the System Administrator role.
I did not do a full test of all possible combinations but I hope this description is sufficient. Otherwise I will be more specific if needed.

**Comment by MscrmTools** [comment]
Hi @n0rthface, thank you for reporting the issue.

I know I may have broken something there... I will double check what is going on

**Comment by n0rthface** [comment]
Hi @MscrmTools, Thank you very much for the quick fix!

**Comment by MscrmTools** [comment]
Deployment is on its way and should be available in the next couple of hours
